import { Box } from "@mui/material";

import { theme } from "@/app/utils/theme.util";
import { ThemeProvider } from "@mui/material/styles";
import "./globals.css";
/*
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* {children} */}
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
